### ISSUE TITLE
Channel flow

### ISSUE THREAD

**Issue by sjtuytc** [tum-pbs/PhiFlow#134]
Hi, how can I create a channel flow as shown in https://nbviewer.org/github/barbagroup/CFDPython/blob/master/lessons/15_Step_12.ipynb?

**Comment by sjtuytc** [comment]
AttributeError: 'NoneType' object has no attribute '__file__'
![image](https://github.com/tum-pbs/PhiFlow/assets/31123348/6f294155-e336-42bc-b062-c6305433ffb4)

**Comment by holl-** [comment]
To run it in a notebook, replace that line with a regular `range` loop, i.e. no `view`.

**Comment by shassan97** [comment]
Hi,
My installed versions are phiflow-2.5.0 phiml-1.1.0
While running the pipe demo, I am getting the following error
```
 * Serving Flask app 'PhiFlow'
 * Debug mode: off
Traceback (most recent call last):
  File "/Users/sheikhmdshakeelhassan/Projects/PhiFlow/demos/pipe.py", line 13, in <module>
    velocity, pressure = fluid.make_incompressible(velocity, solve=Solve(x0=pressure))
  File "/Users/sheikhmdshakeelhassan/envs/torchenv/lib/python3.9/site-packages/phi/physics/fluid.py", line 105, in make_incompressible
    accessible_extrapolation = _accessible_extrapolation(input_velocity.extrapolation)
  File "/Users/sheikhmdshakeelhassan/envs/torchenv/lib/python3.9/site-packages/phi/physics/fluid.py", line 244, in _accessible_extrapolation
    return combine_sides(**{dim: (_accessible_extrapolation(lo), _accessible_extrapolation(hi)) for dim, (lo, hi) in vext.ext.items()})
  File "/Users/sheikhmdshakeelhassan/envs/torchenv/lib/python3.9/site-packages/phi/physics/fluid.py", line 244, in <dictcomp>
    return combine_sides(**{dim: (_accessible_extrapolation(lo), _accessible_extrapolation(hi)) for dim, (lo, hi) in vext.ext.items()})
ValueError: too many values to unpack (expected 2)
```

**Comment by holl-** [comment]
Looks like a bug in PhiML 1.1.0.

Try with `pip install phiml==1.0.1`.

**Comment by holl-** [comment]
I've pushed a fix to `develop`.

```bash
pip uninstall phiflow
pip install git+https://github.com/tum-pbs/PhiFlow.git@develop
```

**Comment by shassan97** [comment]
Thank you for the quick fix. It works now.
